"""update partyParticipant to include role

Revision ID: ab98fd85c3e7
Revises: dd1957bed740
Create Date: 2026-09-20 01:08:19.715247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab98fd85c3e7'
down_revision: Union[str, Sequence[str], None] = 'dd1957bed740'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    participant_role = sa.Enum('HOST', 'GUEST', name='partyparticipantrole')
    participant_role.create(op.get_bind(), checkfirst=True)
    op.add_column('party_participant', sa.Column('role', participant_role, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('party_participant', 'role')
    participant_role = sa.Enum('HOST', 'GUEST', name='partyparticipantrole')
    participant_role.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
