"""auto generate models

Revision ID: ae5994117d46
Revises: ab98fd85c3e7
Create Date: 2026-09-21 00:15:17.574516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae5994117d46'
down_revision: Union[str, Sequence[str], None] = 'ab98fd85c3e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('party', sa.Column('description', sa.String(), nullable=False))
    op.add_column('party', sa.Column('start_time', sa.DateTime(), nullable=False))
    op.add_column('party', sa.Column('end_time', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('party', 'end_time')
    op.drop_column('party', 'start_time')
    op.drop_column('party', 'description')
    # ### end Alembic commands ###
