"""create initial tables

Revision ID: dd1957bed740
Revises: 
Create Date: 2026-09-19 15:54:49.257991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd1957bed740'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('party',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hosted_by', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['hosted_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('party_participant',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('party_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['party_id'], ['party.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('party_id', 'user_id', name='unique_party_user')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('party_participant')
    op.drop_table('party')
    op.drop_table('user')
    # ### end Alembic commands ###
